version: "3.8"
services:
  app:
    container_name: apps 
    build:
      context: ./
      dockerfile: Dockerfile  
    restart: on-failure
    ports:
      - 8082:8081
    expose:
      - 8082
    networks:
      - 'customer_mysql'    

  
## decleare network as external , because we have to join this network to established with database
networks:
  customer_mysql:
    external: true     
