server:
  port: 8081

    
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_store
    #url: jdbc:mysql://mysql-docker:3306/coffee_store    
    username: root
    password: admin
    #password: Password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
